apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ratdwy4ej-python 
  janus-idp.io/tekton: ratdwy4ej-python
  backstage.io/kubernetes-id: ratdwy4ej-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ratdwy4ej-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  